version: 2.0.{build}

skip_tags: false
os: Windows Server 2012 R2
platform: Any CPU
configuration: Release
services:
  - msmq

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

build_script:
  - ps: make\make.ps1 -t build -ap Version:$($env:appveyor_build_version)

test: off

artifacts:
  - path: reports
    name: Reports
  - path: '*.nupkg'
    name: Packages